---
title: "2-deriviitization-efficiency: DDA"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

## Libraries
```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(stringr)
```

## Functions
```{r}
theme_Publication <- function(base_size=16, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family = "")
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               #legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```


## Load data
```{r}
setwd("/Users/ronaldcutler/Dropbox\ (EinsteinMed)/Sidoli-lab/Projects/Single-cell-histone/Analysis/2-derivitization-efficiency/DDA")

outliers <- c("BM20230624_Ultra_IO25_200nl_30min2_ddaPASEF_230620_P4_1_E4_Slot1-1_1_1415",
              "BM20230624_Ultra_IO25_200nl_30min2_ddaPASEF_230620_P4_1_G4_Slot1-1_1_1417")


unmod <- read.csv("MSstats_fix_tryptic.csv")

# number of unique peptides per cell
# total intensity of unique peptides per cell
unmod <- unmod %>%
  filter(!(Run %in% outliers)) %>%
  group_by(Run) %>%
  summarise(n_unmod = sum(!is.na(Intensity)),
            sum_intensity_unmod = sum(Intensity, na.rm = TRUE),
            avg_intensity_unmod = mean(Intensity, na.rm = TRUE))

mod <- read.csv("MSstats_fix_argc.csv")

# number of unique peptides per cell
# total intensity of unique peptides per cell
mod <- mod %>%
  filter(!(Run %in% outliers)) %>%
  group_by(Run) %>%
  summarise(n_mod = sum(!is.na(Intensity)),
            sum_intensity_mod = sum(Intensity, na.rm = TRUE),
            avg_intensity_mod = mean(Intensity, na.rm = TRUE))

var.tryptic <- read.csv("MSstats_var_tryptic.csv")

# number of unique peptides per cell
var.tryptic <- var.tryptic %>%
  filter(!(Run %in% outliers)) %>%
  group_by(Run) %>%
  filter(stringr::str_detect(PeptideSequence, fixed("[56.0260]"))) %>%
  summarise(n_var = sum(!is.na(Intensity)),
            sum_intensity_var = sum(Intensity, na.rm = TRUE),
            avg_intensity_var = mean(Intensity, na.rm = TRUE))

# pair up cells
df <- inner_join(unmod,
                 mod,
                 by = "Run")
df <- inner_join(df,
                 var.tryptic,
                 by = "Run")
```

# Analysis

## Number of peptides
```{r}
df_long <- df %>%
  select(n_unmod, n_mod, n_var, Run) %>%
  pivot_longer(cols = -Run, names_to = "condition", values_to = "value") %>%
  mutate(condition = factor(condition, levels = c("n_unmod", 'n_var', "n_mod")))

pdf("unique_peptides_paired.pdf",
    width = 5,
    height = 5)
ggpaired(df_long, x = "condition", y = "value",
         fill = "condition",
         line.fill =  "gray", 
         line.size = 0.4,
         boxplot.geom = c("boxplot", "jitter"),
         id = "Run") +
  stat_compare_means(method = "anova", paired = TRUE) +
  labs(x = NULL, y = "# Unique Peptides") +
  theme_Publication(base_size = 14) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  scale_x_discrete(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme(legend.position = "none")
dev.off()

pdf("unique_peptides_bar.pdf",
    width = 5,
    height = 5)
ggplot(df_long, aes(x = Run, y = value, fill = condition)) +
  geom_bar(stat = "identity") +
  labs(x = "Cell", y = "# Unique Peptides") +
  theme_Publication(base_size = 14) +
  scale_x_discrete(labels = c("D2", "E2", "F2", "G2")) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
    theme(legend.position="bottom", 
        legend.box="vertical", 
        legend.margin=margin(),
        legend.title = element_blank(),
        legend.text = element_text(size = 10))
dev.off()
```

## Percent of peptides
```{r}
df <- df %>%
  mutate(percent_n_unmod = n_unmod / (n_unmod + n_mod + n_var) * 100,
         percent_n_var = n_var / (n_unmod + n_mod + n_var) * 100,
         percent_n_mod = n_mod / (n_unmod + n_mod + n_var) * 100)
  
df_long <- df %>%
  select(Run, percent_n_unmod, percent_n_var, percent_n_mod) %>%
  pivot_longer(cols = -Run, names_to = "type", values_to = "percent") %>%
  mutate(type = factor(type, levels = c("percent_n_unmod", "percent_n_var", "percent_n_mod")))

pdf("percent_peptides_paired.pdf",
    width = 5,
    height = 5)
ggpaired(df_long, x = "type", y = "percent",
         fill =  "type",
         line.fill =  "gray", 
         line.size = 0.4,
         boxplot.geom = c("boxplot", "jitter"),
         id = "Run") +
  stat_compare_means(method = "anova", paired = TRUE) +
  labs(x = NULL, y = "% Unique Peptides") +
  theme_Publication(base_size = 14) +
  scale_x_discrete(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme(legend.position = "none") +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) # Add percent sign 
dev.off()

pdf("percent_peptides_bar.pdf",
    width = 5,
    height = 5)
ggplot(df_long, aes(x = Run, y = percent, fill = type)) +
  geom_bar(stat = "identity") +
  labs(x = "Cell", y = "# Unique Peptides") +
  theme_Publication(base_size = 14) +
  scale_x_discrete(labels = c("D2", "E2", "F2", "G2")) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
    theme(legend.position="bottom", 
        legend.box="vertical", 
        legend.margin=margin(),
        legend.title = element_blank(),
        legend.text = element_text(size = 10)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) # Add percent sign 
dev.off()
```

## Summed intensity
```{r}
df_long <- df %>%
  select(sum_intensity_unmod, sum_intensity_mod, sum_intensity_var, Run) %>%
  pivot_longer(cols = -Run, names_to = "condition", values_to = "value") %>%
  mutate(condition = factor(condition, levels = c("sum_intensity_unmod", "sum_intensity_var", "sum_intensity_mod")))

pdf("summed_intensity_paired.pdf",
    width = 5,
    height = 5)
ggpaired(df_long, x = "condition", y = "value",
         fill =  "condition",
         line.fill =  "gray", 
         line.size = 0.4,
         boxplot.geom = c("boxplot", "jitter"),
         id = "Run") +
  stat_compare_means(method = "anova", paired = TRUE) +
  labs(x = NULL, y = "Summed MS1 Intensity") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme_Publication(base_size = 14) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme(legend.position = "none")
dev.off()


pdf("summed_intensity_bar.pdf",
    width = 5,
    height = 5)
ggplot(df_long, aes(x = Run, y = value, fill = condition)) +
  geom_bar(stat = "identity") +
  labs(x = "Cell", y = "Summed MS1 Intensity") +
  theme_Publication(base_size = 14) +
  scale_x_discrete(labels = c("D2", "E2", "F2", "G2")) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
    theme(legend.position="bottom", 
        legend.box="vertical", 
        legend.margin=margin(),
        legend.title = element_blank(),
        legend.text = element_text(size = 10))
dev.off()
```

## Mean intensity
```{r}
df_long <- df %>%
  select(avg_intensity_unmod, avg_intensity_mod, avg_intensity_var, Run) %>%
  pivot_longer(cols = -Run, names_to = "condition", values_to = "value") %>%
  mutate(condition = factor(condition, levels = c("avg_intensity_unmod", "avg_intensity_var", "avg_intensity_mod")))

pdf("mean_intensity_paired.pdf",
    width = 5,
    height = 5)
ggpaired(df_long, x = "condition", y = "value",
         fill =  "condition",
         line.fill =  "gray", 
         line.size = 0.4,
         boxplot.geom = c("boxplot", "jitter"),
         id = "Run") +
  stat_compare_means(method = "anova", paired = TRUE) +
  labs(x = NULL, y = "Mean MS1 Intensity") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme_Publication(base_size = 14) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  theme(legend.position = "none")
dev.off()


pdf("mean_intensity_bar.pdf",
    width = 5,
    height = 5)
ggplot(df_long, aes(x = Run, y = value, fill = condition)) +
  geom_bar(stat = "identity") +
  labs(x = "Cell", y = "Mean MS1 Intensity") +
  theme_Publication(base_size = 14) +
  scale_fill_Publication(labels = c("Unmodified", "Underpropionylated", "Propionylated")) +
  scale_x_discrete(labels = c("D2", "E2", "F2", "G2")) +
  theme(legend.position="bottom", 
        legend.box="vertical", 
        legend.margin=margin(),
        legend.title = element_blank(),
        legend.text = element_text(size = 10))
dev.off()
```