---
title: "2-derivitization-efficiency: auto"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

## Libraries
```{r}
library(SummarizedExperiment)
library(tidyr)
library(dplyr)
library(tibble)
library(ggplot2)
library(pheatmap)
library(ggpubr)
library(reshape2)
```

## Functions
```{r}
source("/Users/ronaldcutler/Dropbox\ (EinsteinMed)/Sidoli-lab/Projects/Single-cell-histone/Analysis/functions.R")
```

## Load data
```{r}
# metadata
setwd("/Users/ronaldcutler/Dropbox\ (EinsteinMed)/Sidoli-lab/Projects/Single-cell-histone/Analysis/1-data/single-cell")

coldata <- read.csv("sample-table.csv", 
               header = TRUE,
               stringsAsFactors = TRUE)
coldata[] <- lapply(coldata, as.factor) # make all vars factors

# skyline output
setwd("/Users/ronaldcutler/Dropbox\ (EinsteinMed)/Sidoli-lab/Projects/Single-cell-histone/Analysis/1-data/single-cell/intensities")

df <- read.csv("240125_Skyline_SC_export_auto1_June_prop_efficiency.csv", 
               header = TRUE,
               stringsAsFactors = TRUE,
               na.strings = "#N/A")

# load
obj <- load_skyline_prop_eff_summarized_experiment(df, coldata)


# change replicate 4 to 3 to make it easier to read
obj$replicate <- as.character(obj$replicate)
obj$replicate[obj$replicate == 4] <- 3
obj$replicate <- factor(obj$replicate)
```

## Save object
```{r}
setwd("/Users/ronaldcutler/Dropbox\ (EinsteinMed)/Sidoli-lab/Projects/Single-cell-histone/Analysis/2-derivitization-efficiency/DIA/auto")

saveRDS(obj, "obj.RDS")
```

# MS1 Intensity of different derivitized forms of the most abundant histone peptide

## Cells
```{r}
# by peptide
df <- assay(obj, "MS1") %>% 
  rownames_to_column("id") %>%
  pivot_longer(
    cols = -id,
    names_to = "variable",
    values_to = "value") %>%
  merge(as.data.frame(colData(obj)), by.x = "variable", by.y = "row.names")  %>%
  subset(type == "cell")

# set the NOT FOUND peptides to 0, since they are background

df$id <- gsub(" \\(NOT FOUND\\)", "", df$id)
df$id <- factor(df$id, levels = rev(c("Full prop (ArgC)",
                                  "No prop (fully tryptic)",
                                  "No prop (tryptic with 1 MC)",
                                  "No prop (tryptic with 2 MC)",
                                  "1st round underprop (fully tryptic)",
                                  "1st round underprop (tryptic with 1 MC)",
                                  "2nd round underprop (ArgC)",
                                  "Overprop on T (ArgC)")))

# all the different cell inputs
pdf("MS1_distribution_cell.pdf",
    width = 8,
    height = 8)
ggplot(df, aes(x = id, y = value, fill = as.factor(multiplier))) +
  geom_boxplot() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(title = "", x = "Peptide type", y = "MS1 intensity", fill = "Cell #")
dev.off()

pdf("MS1_distribution_cell_log.pdf",
    width = 8,
    height = 8)
ggplot(df, aes(x = id, y = value, fill = as.factor(multiplier))) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  labs(title = "", x = "Peptide type", y = "MS1 intensity", fill = "Cell #")
dev.off()

# only show the 100 cell inputs
pdf("MS1_distribution_cell_100cell.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "100"), aes(x = id, y = value, color = id)) +
  geom_point() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_cell_100cell_log.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "100"), aes(x = id, y = value, color = id)) +
  geom_point() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

# only show the single cell inputs
pdf("MS1_distribution_cell_1cell.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "1"), aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_cell_1cell_log.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "1"), aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

# summarize all the different inputs
pdf("MS1_distribution_cell_summary.pdf",
    width = 7,
    height = 5)
ggplot(df, aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_cell_summary_log.pdf",
    width = 7,
    height = 5)
ggplot(df, aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()
```

## Histone standards
```{r}
# by peptide
df <- assay(obj, "MS1") %>% 
  rownames_to_column("id") %>%
  pivot_longer(
    cols = -id,
    names_to = "variable",
    values_to = "value") %>%
  merge(as.data.frame(colData(obj)), by.x = "variable", by.y = "row.names")  %>%
  subset(type == "standard")

# set the NOT FOUND peptides to 0, since they are background

df$id <- gsub(" \\(NOT FOUND\\)", "", df$id)
df$id <- factor(df$id, levels = rev(c("Full prop (ArgC)",
                                  "No prop (fully tryptic)",
                                  "No prop (tryptic with 1 MC)",
                                  "No prop (tryptic with 2 MC)",
                                  "1st round underprop (fully tryptic)",
                                  "1st round underprop (tryptic with 1 MC)",
                                  "2nd round underprop (ArgC)",
                                  "Overprop on T (ArgC)")))

# all the different standard inputs
pdf("MS1_distribution_standard.pdf",
    width = 8,
    height = 8)
ggplot(df, aes(x = id, y = value, fill = as.factor(multiplier))) +
  geom_boxplot() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(title = "", x = "Peptide type", y = "MS1 intensity", fill = "standard #")
dev.off()

pdf("MS1_distribution_standard_log.pdf",
    width = 8,
    height = 8)
ggplot(df, aes(x = id, y = value, fill = as.factor(multiplier))) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  labs(title = "", x = "Peptide type", y = "MS1 intensity", fill = "standard #")
dev.off()

# only show the 100 standard inputs
pdf("MS1_distribution_standard_100standard.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "100"), aes(x = id, y = value, color = id)) +
  geom_point() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_standard_100standard_log.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "100"), aes(x = id, y = value, color = id)) +
  geom_point() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

# only show the single standard inputs
pdf("MS1_distribution_standard_1standard.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "1"), aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_standard_1standard_log.pdf",
    width = 7,
    height = 5)
ggplot(subset(df, multiplier == "1"), aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

# summarize all the different inputs
pdf("MS1_distribution_standard_summary.pdf",
    width = 7,
    height = 5)
ggplot(df, aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()

pdf("MS1_distribution_standard_summary_log.pdf",
    width = 7,
    height = 5)
ggplot(df, aes(x = id, y = value, fill = id)) +
  geom_boxplot() +
  scale_y_log10() +
  coord_flip() +
  theme_Publication() +
  scale_fill_Publication() +
  theme(legend.position = "none") +
  labs(title = "", x = "Peptide type", y = "MS1 intensity")
dev.off()
```