---
title: "3-calibration-curves: auto - cells"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation

## Libraries
```{r}
library(SummarizedExperiment)
library(tidyr)
library(dplyr)
library(tibble)
library(ggplot2)
library(pheatmap)
library(ggpubr)
library(reshape2)
library(cowplot) 
```

## Functions
```{r}
source("~/single-cell-histone-ptm/functions.R")
```

## Load data
```{r}
# metadata
setwd("~/single-cell-histone-ptm/1-data/single-cell")

coldata <- read.csv("sample-table.csv", 
               header = TRUE,
               stringsAsFactors = TRUE)
coldata[] <- lapply(coldata, as.factor) # make all vars factors

# skyline output
setwd("~/single-cell-histone-ptm/1-data/single-cell/intensities")

# combine all plates
df.1 <- read.csv("241113_Skyline_SC_export_auto1_cells.csv", 
               header = TRUE,
               stringsAsFactors = TRUE,
               na.strings = "#N/A")

df.2 <- read.csv("241106_Skyline_SC_export_auto2_auto4_cells.csv", 
               header = TRUE,
               stringsAsFactors = TRUE,
               na.strings = "#N/A")

df.combine <- rbind(df.1, df.2)

# filter peptides
df.combine.filter <- filter_peptides_skyline(df.combine)

# deconvolute isobaric H4 peptides using fragments
df.combine.filter.deconv <- deconvolute_h4(df.combine.filter)

# combine into summarized experiment object
obj <- load_summarized_experiment_skyline(df.combine.filter.deconv, coldata)

# change replicate 4 to 3 to make it easier to read
obj$replicate <- as.character(obj$replicate)
obj$replicate[obj$replicate == 4] <- 3
obj$replicate <- factor(obj$replicate)
```

## Save object
```{r}
setwd("~/single-cell-histone-ptm/3-calibration-curves/auto/cells/unfiltered")

saveRDS(obj, "obj.RDS")
```

# Plot calibration curves

## MS1

### All peptidoforms
```{r}
setwd("~/single-cell-histone-ptm/3-calibration-curves/auto/cells/unfiltered")

# all replicates
df <- assay(obj, "MS1") %>% 
  rownames_to_column("id") %>%
  pivot_longer(
    cols = -id, # This keeps the 'id' column fixed
    names_to = "variable",
    values_to = "value") %>%
  merge(as.data.frame(colData(obj)), by.x = "variable", by.y = "row.names") %>%
  filter(multiplier != 100)
df$id <- gsub(";", " ", df$id)
 
pdf("MS1_calibration_curve_all.pdf",
    width = 25,
    height = 25)
ggplot(df, aes(x = as.numeric(as.character(multiplier)), y = value, color = as.factor(replicate))) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  labs(title = "", x = "Cell #", y = "MS1 intensity") +
  facet_wrap(.~id, scales = "free", labeller = labeller(id = label_wrap_gen(20))) +
  theme_Publication(base_size = 12) +
  scale_x_continuous(breaks = c(0,1,2,4,8)) +
  theme(
    axis.title.x = element_text(size = 32),
    axis.title.y = element_text(size = 32),
    axis.text = element_text(size = 16),
    legend.title = element_text(size = 32),
    legend.text = element_text(size = 32),
    strip.text = element_text(size = 12)
  )
dev.off()

# replicate 1
pdf("MS1_calibration_curve_replicate_1.pdf",
    width = 25,
    height = 25)
ggplot(subset(df, replicate == 1), aes(x = as.numeric(as.character(multiplier)), y = value)) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  facet_wrap(.~id, scales = "free", labeller = labeller(id = label_wrap_gen(20))) +
  theme_Publication(base_size = 12) +
  labs(title = "", x = "Cell #", y = "MS1 intensity") +
  scale_x_continuous(breaks = c(0,1,2,4,8))
dev.off()

# replicate 2
pdf("MS1_calibration_curve_replicate_2.pdf",
    width = 25,
    height = 25)
ggplot(subset(df, replicate == 2), aes(x = as.numeric(as.character(multiplier)), y = value)) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  facet_wrap(.~id, scales = "free", labeller = labeller(id = label_wrap_gen(20))) +
  theme_Publication(base_size = 12) +
  labs(title = "", x = "Cell #", y = "MS1 intensity") +
  scale_x_continuous(breaks = c(0,1,2,4,8))
dev.off()

# replicate 4 (labeld as 3)
pdf("MS1_calibration_curve_replicate_4.pdf",
    width = 25,
    height = 25)
ggplot(subset(df, replicate == 3), aes(x = as.numeric(as.character(multiplier)), y = value)) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor() +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  facet_wrap(.~id, scales = "free", labeller = labeller(id = label_wrap_gen(20))) +
  theme_Publication(base_size = 12) +
  labs(title = "", x = "Cell #", y = "MS1 intensity") +
  scale_x_continuous(breaks = c(0,1,2,4,8))
dev.off()

# distribution of R values
df$multiplier <- as.numeric(as.character(df$multiplier))
df.R <- df %>%
  group_by(id, replicate) %>%
  summarise(
    correlation = if(sum(!is.na(value) & !is.na(multiplier) & is.finite(value) & is.finite(multiplier)) > 1) 
                    cor.test(value, multiplier, use = "complete.obs")$estimate 
                  else NA,
    p_value = if(sum(!is.na(value) & !is.na(multiplier) & is.finite(value) & is.finite(multiplier)) > 1) 
                cor.test(value, multiplier, use = "complete.obs")$p.value 
              else NA,
    .groups = "drop"  # Drops the grouping structure from the result
  )

pdf("MS1_calibration_curve_correlations.pdf",
    width = 4,
    height = 3.5)
violin_plot <- ggplot(df.R, aes(x = as.factor(replicate), y = correlation, fill = as.factor(replicate))) +
  geom_violin(outlier.shape = NA) +
  geom_jitter(aes(color = p_value), alpha = 0.6) +
  geom_hline(yintercept = 0.8, linetype='dashed') +
  scale_color_gradient(low = "black", high = "white") +
  guides(fill = FALSE) +
  theme_Publication(base_size = 12) +
  theme(legend.position = "top") +
  labs(x = "Replicate", y = "Pearson R", color = "p-value") +
  theme(legend.text = element_text(size = 10),
        legend.key.size = unit(0.5, 'cm'))



histogram_plot <- ggplot(df.R, aes(x = correlation, fill = as.factor(replicate))) +
  geom_histogram(position = "dodge", binwidth = 0.1, alpha = 1) + # Adjust binwidth as needed
  coord_flip() + # Flip the axes to make the histogram vertical
  theme_void() +
  guides(fill = FALSE) 

# Align the plots side by side
plot_grid(violin_plot, histogram_plot, axis = "tb", align = 'hv', ncol = 2, rel_widths = c(2, 1))
dev.off()


# output distribution to be used for filtering downstream
write.csv(df.R, "MS1_calibration_curve_correlations.csv", row.names = FALSE)
```

### Representative peptidoforms
```{r}
# all replicates
df <- assay(obj, "MS1") %>% 
  rownames_to_column("id") %>%
  pivot_longer(
    cols = -id, # This keeps the 'id' column fixed
    names_to = "variable",
    values_to = "value") %>%
  merge(as.data.frame(colData(obj)), by.x = "variable", by.y = "row.names") %>%
  filter(multiplier != 100)
df$id <- gsub(";", " ", df$id)

# subset peptides
rep_peptides <- c("H2A1B-K13[un] K15[ac]", "H31-K9[me2] K14[un]","H31-K18[un] K23[ac]", "H4-K5[ac] K8[un] K12[ac] K16[un]")
facet_labels <- c("H2AK15Ac", "H3K9Me2", "H3K23Ac", "H4K5AcK12Ac")
names(facet_labels) <- rep_peptides
df <- subset(df, id %in% rep_peptides)

pdf("MS1_calibration_curve_representative.pdf",
    width = 7,
    height = 3.5)
ggplot(df, aes(x = as.numeric(as.character(multiplier)), y = value, color = as.factor(replicate))) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor(size = 2) +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  labs(title = "", x = "Cell #", y = "MS1 Intensity") +
  facet_wrap(.~id, scales = "free", nrow = 1, labeller = labeller(id = facet_labels)) +
  theme_Publication(base_size = 12) +
  scale_x_continuous(breaks = c(0,1,2,4,8)) +
  theme(legend.position = "top") +
  guides(color = guide_legend( 
    override.aes=list(shape = 19))) 
dev.off() 


pdf("MS1_calibration_curve_single_transparent.pdf",
    width = 3,
    height = 3.5)
ggplot(subset(df, id == "H31-K9[me2] K14[un]"), aes(x = as.numeric(as.character(multiplier)), y = value, color = as.factor(replicate))) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_cor(size = 3) +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_discrete(name = "Replicate") +
  guides(fill = guide_legend(override.aes = list(shape = NA))) +
  labs(title = "", x = "Cell #", y = "MS1 Intensity") +
  facet_wrap(.~id, scales = "free", nrow = 1, labeller = labeller(id = facet_labels)) +
  theme_Publication(base_size = 12) +
  scale_x_continuous(breaks = c(0,1,2,4,8)) +
  theme(legend.position = "top",
        plot.background = element_rect(fill = "transparent", colour = NA), # transparent background
        panel.background = element_rect(fill = "transparent", colour = NA), # transparent panel
        legend.background = element_rect(fill = "transparent", colour = NA), # transparent legend
        legend.key = element_rect(fill = "transparent", colour = NA)) + # transparent legend keys
  guides(color = guide_legend(override.aes=list(shape = 19))) 
dev.off()
```